services:
  backend:
    image: ccstiet/smartdrive
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6782:6782"
    # network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
