services:
  backend:
    image: ccstiet/smartdrive
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6782:6782"
    volumes:
      - ./BACKEND/upload_foldet/:/app/BACKEND/upload_folder
    network_mode: "host"
