services:
  python_app:
    build: .
    container_name: python_script_container
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    command: python main.py  # Run the script
